---
galaxy_info:
  role_name: post_migration_validation
  author: Auto Domain Migration Project
  description: Validates successful migration of AD objects
  license: MIT
  min_ansible_version: '2.12'
  platforms:
    - name: Windows
      versions:
        - 2019
        - 2022

dependencies: []

