---
# Role metadata
galaxy_info:
  role_name: admt_prerequisites
  author: Auto Domain Migration Project
  description: Prepares environment for ADMT-based domain migration
  license: MIT
  min_ansible_version: '2.12'
  platforms:
    - name: Windows
      versions:
        - 2019
        - 2022

dependencies: []

