---
- name: Execute rollback commands on Linux
  when:
    - ansible_os_family != 'Windows'
    - rollback_commands | length > 0
  ansible.builtin.shell: "{{ item }}"
  loop: "{{ rollback_commands }}"
  failed_when: false

- name: Execute rollback commands on Windows
  when:
    - ansible_os_family == 'Windows'
    - rollback_commands | length > 0
  ansible.windows.win_shell: "{{ item }}"
  loop: "{{ rollback_commands }}"
  failed_when: false

- name: Record rollback status
  ansible.builtin.lineinfile:
    path: "{{ artifacts_base }}/status.jsonl"
    line: "{{ {'host': inventory_hostname, 'phase': 'rollback', 'wave': rollback_wave, 'timestamp': ansible_date_time.iso8601} | to_json }}"
    create: true
  delegate_to: localhost
