# Alertmanager Configuration for Self-Healing
# Purpose: Route alerts to AWX for automatic remediation

apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      routes:
      - match:
          severity: critical
          self_healing_enabled: "true"
        receiver: 'awx-webhook'
      - match:
          severity: warning
        receiver: 'email'

    receivers:
    - name: 'default'
      webhook_configs:
      - url: 'http://alertmanager-webhook-receiver.observability.svc.cluster.local:8080/alerts'
        send_resolved: true

    - name: 'awx-webhook'
      webhook_configs:
      - url: 'http://awx-migration-service.awx.svc.cluster.local/api/v2/job_templates/self-healing/launch/'
        send_resolved: true
        http_config:
          basic_auth:
            username: admin
            password: ${AWX_ADMIN_PASSWORD}

    - name: 'email'
      email_configs:
      - to: 'admin@example.com'
        from: 'alertmanager@migration.example.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alertmanager@example.com'
        auth_password: '${SMTP_PASSWORD}'

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']

