# AWX Operator Installation
# Deploy this first to install the AWX Operator

apiVersion: v1
kind: Namespace
metadata:
  name: automation
  labels:
    name: automation
    purpose: ansible-automation

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-operator
  namespace: automation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: awx-operator
  namespace: automation
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "services/finalizers", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get"]
  - apiGroups: ["awx.ansible.com"]
    resources: ["*"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-operator
  namespace: automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awx-operator
subjects:
  - kind: ServiceAccount
    name: awx-operator
    namespace: automation

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-operator
  namespace: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      name: awx-operator
  template:
    metadata:
      labels:
        name: awx-operator
    spec:
      serviceAccountName: awx-operator
      containers:
        - name: awx-operator
          image: quay.io/ansible/awx-operator:2.10.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "awx-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

