---
# Playbook: 05_validation.yml
# Purpose: Validate successful migration of AD objects
# Usage: ansible-playbook -i inventory/hosts.ini playbooks/05_validation.yml -e "migration_batch_id=batch_001"

- name: Post-Migration Validation
  hosts: target_dc
  gather_facts: yes
  
  pre_tasks:
    - name: Verify migration batch ID is provided
      ansible.builtin.fail:
        msg: "Migration batch ID must be provided: -e migration_batch_id=<batch_id>"
      when: migration_batch_id is not defined

    - name: Display validation information
      ansible.builtin.debug:
        msg: |
          ========================================
          Starting Post-Migration Validation
          ========================================
          Batch ID: {{ migration_batch_id }}
          Target Domain: {{ target_domain_fqdn }}
          ========================================

    - name: Load migrated objects list
      ansible.builtin.set_fact:
        migrated_users: "{{ lookup('file', '/opt/ansible/data/batches/' + migration_batch_id + '_users.json', errors='ignore') | default('[]') | from_json }}"
        migrated_computers: "{{ lookup('file', '/opt/ansible/data/batches/' + migration_batch_id + '_computers.json', errors='ignore') | default('[]') | from_json }}"
        migrated_groups: "{{ lookup('file', '/opt/ansible/data/batches/' + migration_batch_id + '_groups.json', errors='ignore') | default('[]') | from_json }}"

  tasks:
    - name: Run validation role
      ansible.builtin.include_role:
        name: post_migration_validation
      vars:
        validation_output_dir: "/opt/ansible/data/validation/{{ migration_batch_id }}"
      tags:
        - validation

  post_tasks:
    - name: Collect validation results
      ansible.builtin.set_fact:
        validation_passed: "{{ (user_validation.failed | default(false) == false) and (computer_validation.failed | default(false) == false) and (group_validation.failed | default(false) == false) }}"

    - name: Display validation summary
      ansible.builtin.debug:
        msg: |
          ========================================
          Validation Complete for Batch {{ migration_batch_id }}
          ========================================
          Status: {{ 'PASSED' if validation_passed else 'FAILED' }}
          
          Results available at:
          /opt/ansible/data/validation/{{ migration_batch_id }}/validation_report.html
          
          {{ 'Migration successful! You can proceed with the next wave.' if validation_passed else 'Validation failed. Review logs and consider rollback.' }}
          ========================================

