---
- name: Rollback server migration
  hosts: source_servers:target_servers
  gather_facts: true
  vars:
    wave_id: "{{ wave_id | default('wave1') }}"
  tasks:
    - name: Execute rollback role
      ansible.builtin.include_role:
        name: server_rollback
