---
- name: Full server migration workflow
  hosts: localhost
  gather_facts: false
  vars:
    wave_id: "{{ wave_id | default('wave1') }}"
  tasks:
    - name: Run discovery phase
      ansible.builtin.include_playbook: 00_discovery.yml

    - name: Run prerequisites phase
      ansible.builtin.include_playbook: 01_prerequisites.yml

    - name: Start replication
      ansible.builtin.include_playbook: 02_replication.yml

    - name: Await operator approval
      ansible.builtin.pause:
        prompt: |
          Wave {{ wave_id }} replication complete. Press Enter to begin cutover or Ctrl+C to abort.

    - name: Execute cutover
      ansible.builtin.include_playbook: 03_cutover.yml

    - name: Validate workloads
      ansible.builtin.include_playbook: 04_validation.yml

    - name: Review validation results
      ansible.builtin.debug:
        msg: "Validation artifacts stored under artifacts/validation/{{ wave_id }}-*.yml"
