#cloud-config
# PostgreSQL Server Setup (vSphere)
# Author: Adrian Johnson <adrian207@gmail.com>

package_update: true
package_upgrade: true

packages:
  - postgresql-15
  - postgresql-contrib-15
  - python3-psycopg2
  - open-vm-tools

write_files:
  - path: /etc/postgresql/15/main/pg_hba.conf
    content: |
      # PostgreSQL Client Authentication Configuration
      local   all             postgres                                peer
      local   all             all                                     peer
      host    all             all             0.0.0.0/0               md5
      host    all             all             ::/0                    md5

  - path: /etc/postgresql/15/main/postgresql.conf
    content: |
      # PostgreSQL Configuration
      listen_addresses = '*'
      port = 5432
      max_connections = 100
      shared_buffers = 256MB
      effective_cache_size = 1GB
      maintenance_work_mem = 128MB
      checkpoint_completion_target = 0.9
      wal_buffers = 16MB
      default_statistics_target = 100
      random_page_cost = 1.1
      effective_io_concurrency = 200
      work_mem = 16MB
      min_wal_size = 1GB
      max_wal_size = 4GB
      logging_collector = on
      log_directory = 'log'
      log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
      log_rotation_age = 1d
      log_rotation_size = 100MB
      log_line_prefix = '%m [%p] %q%u@%d '
      log_timezone = 'UTC'
      datestyle = 'iso, mdy'
      timezone = 'UTC'
      lc_messages = 'en_US.UTF-8'
      lc_monetary = 'en_US.UTF-8'
      lc_numeric = 'en_US.UTF-8'
      lc_time = 'en_US.UTF-8'
      default_text_search_config = 'pg_catalog.english'

  - path: /usr/local/bin/init-databases.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # Initialize PostgreSQL databases
      
      sudo -u postgres psql << EOF
      -- Create admin user
      CREATE USER ${admin_username} WITH PASSWORD '${postgres_password}';
      ALTER USER ${admin_username} WITH SUPERUSER;
      
      -- Create databases
      CREATE DATABASE guacamole_db OWNER ${admin_username};
      CREATE DATABASE migration_state OWNER ${admin_username};
      CREATE DATABASE migration_telemetry OWNER ${admin_username};
      
      -- Grant privileges
      GRANT ALL PRIVILEGES ON DATABASE guacamole_db TO ${admin_username};
      GRANT ALL PRIVILEGES ON DATABASE migration_state TO ${admin_username};
      GRANT ALL PRIVILEGES ON DATABASE migration_telemetry TO ${admin_username};
      EOF
      
      echo "PostgreSQL databases initialized!"

runcmd:
  # Enable and start open-vm-tools
  - systemctl enable open-vm-tools
  - systemctl start open-vm-tools
  
  # Create data directory on second disk (if exists)
  - |
    if [ -b /dev/sdb ]; then
      mkfs.ext4 /dev/sdb
      mkdir -p /var/lib/postgresql_data
      mount /dev/sdb /var/lib/postgresql_data
      echo "/dev/sdb /var/lib/postgresql_data ext4 defaults 0 2" >> /etc/fstab
      chown -R postgres:postgres /var/lib/postgresql_data
    fi
  
  # Restart PostgreSQL with new configuration
  - systemctl restart postgresql
  - systemctl enable postgresql
  
  # Wait for PostgreSQL to start
  - sleep 10
  
  # Initialize databases
  - /usr/local/bin/init-databases.sh
  
  # Create backup directory
  - mkdir -p /var/backups/postgresql
  - chown postgres:postgres /var/backups/postgresql

final_message: "PostgreSQL server is ready! Listening on all interfaces"


