---
# Role: admt_prerequisites
# Purpose: Prepare environment for ADMT migration
# Dependencies: None
# Target: Domain Controllers (Source and Target)

- name: Install ADMT prerequisites
  block:
    - name: Verify PowerShell version
      ansible.windows.win_shell: $PSVersionTable.PSVersion.Major
      register: ps_version
      failed_when: ps_version.stdout | int < 5

    - name: Check Windows Server version
      ansible.windows.win_shell: |
        (Get-CimInstance Win32_OperatingSystem).Caption
      register: os_version

    - name: Display OS version
      ansible.builtin.debug:
        msg: "Target OS: {{ os_version.stdout_lines[0] }}"

    - name: Install RSAT AD PowerShell module
      ansible.windows.win_feature:
        name:
          - RSAT-AD-PowerShell
          - RSAT-ADDS
          - RSAT-AD-AdminCenter
        state: present
        include_management_tools: true
      when: "'Target' in inventory_hostname"

    - name: Create ADMT working directory
      ansible.windows.win_file:
        path: C:\ADMT
        state: directory

    - name: Create ADMT logs directory
      ansible.windows.win_file:
        path: C:\ADMT\Logs
        state: directory

    - name: Create ADMT scripts directory
      ansible.windows.win_file:
        path: C:\ADMT\Scripts
        state: directory

    - name: Create ADMT batches directory
      ansible.windows.win_file:
        path: C:\ADMT\Batches
        state: directory

    - name: Copy ADMT PowerShell module
      ansible.windows.win_copy:
        src: "{{ playbook_dir }}/../files/ADMT-Functions.psm1"
        dest: C:\ADMT\Scripts\ADMT-Functions.psm1

    - name: Set execution policy for scripts
      ansible.windows.win_shell: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force
      changed_when: false

    - name: Check if ADMT is already installed
      ansible.windows.win_stat:
        path: "C:\\Program Files\\Active Directory Migration Tool\\ADMT.exe"
      register: admt_installed

    - name: Display ADMT installation status
      ansible.builtin.debug:
        msg: "ADMT Installed: {{ admt_installed.stat.exists }}"

    - name: Verify domain membership
      ansible.windows.win_shell: |
        $domain = (Get-WmiObject Win32_ComputerSystem).Domain
        Write-Output $domain
      register: domain_membership

    - name: Display domain membership
      ansible.builtin.debug:
        msg: "Domain: {{ domain_membership.stdout_lines[0] }}"

  tags:
    - prerequisites
    - admt_setup

