---
# Default variables for admt_prerequisites role

# Azure Storage for ADMT binaries
azure_storage_account: "{{ lookup('env', 'AZURE_STORAGE_ACCOUNT') }}"
azure_storage_sas_token: "{{ lookup('env', 'AZURE_STORAGE_SAS_TOKEN') }}"

# ADMT Installation
install_pes: false
admt_version: "3.2"

# Working directories
admt_working_dir: C:\ADMT
admt_logs_dir: C:\ADMT\Logs
admt_scripts_dir: C:\ADMT\Scripts

# Migration settings
admt_migration_database: "ADMT"
admt_database_server: "{{ target_dc_hostname }}"

