---
job_templates:
  - name: "Server Migration - Discovery"
    inventory: "Server Migration Inventory"
    project: "Server Migration"
    playbook: "playbooks/00_discovery.yml"
    survey_enabled: false
  - name: "Server Migration - Prerequisites"
    inventory: "Server Migration Inventory"
    project: "Server Migration"
    playbook: "playbooks/01_prerequisites.yml"
  - name: "Server Migration - Replication"
    inventory: "Server Migration Inventory"
    project: "Server Migration"
    playbook: "playbooks/02_replication.yml"
  - name: "Server Migration - Cutover"
    inventory: "Server Migration Inventory"
    project: "Server Migration"
    playbook: "playbooks/03_cutover.yml"
  - name: "Server Migration - Validation"
    inventory: "Server Migration Inventory"
    project: "Server Migration"
    playbook: "playbooks/04_validation.yml"
  - name: "Server Migration - Rollback"
    inventory: "Server Migration Inventory"
    project: "Server Migration"
    playbook: "playbooks/99_rollback.yml"
