# Namespaces for Tier 3 Enterprise Platform
# Purpose: Organize resources by function

apiVersion: v1
kind: Namespace
metadata:
  name: awx
  labels:
    name: awx
    tier: "3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
    tier: "3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
    tier: "3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    tier: "3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    tier: "3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    tier: "3"

